# Generated by Django 4.2.7 on 2023-11-09 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=20)),
                ("nom", models.CharField(default="", max_length=20)),
                ("prenom", models.CharField(default="", max_length=20)),
                ("adresse_mail", models.EmailField(default="", max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilisateur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horodatage",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Date et heure de la transaction",
                    ),
                ),
                ("montant_btc", models.DecimalField(decimal_places=8, max_digits=10)),
                ("montant_xof", models.DecimalField(decimal_places=2, max_digits=10)),
                ("operateur", models.CharField(default="", max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[("Vente", "Vente"), ("Achat", "Achat")],
                        default="Achat",
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.utilisateur",
                    ),
                ),
            ],
        ),
    ]
