# Generated by Django 4.2.7 on 2023-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.AddField(
            model_name="transaction",
            name="users",
            field=models.ManyToManyField(to="authentication.utilisateur"),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="solde",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
